#' Print EDY objects.
#'
#' @title Print EDY objects
#' @param x An EDY object generated by the function \code{getEDY}.
#' 
#' @export print.EDY 
#' @return A description of the contents of the EDY object (\code{x}).


print.EDY <- function(x, ...){
  cat("\nEDY object\nGenerated by `getEDY`\nContains information about males only from 
      the original data set\n")
  cat("$EDY: factor indicating whether each individual has EDY or not\n  NO: ")
  cat(table(x$EDY)[1])
  cat("  YES: ")
  cat(table(x$EDY)[2])
  cat("\n$EDYcontinuous: individual relative expression of chrY")
  cat("\n$threshold: ")
  cat(x$threshold)
  if (names(x)[4]=="eSet"){
    cat("\n$eSet:\n")
    print(x$eSet)
  } else if (names(x)[4]=="RangedSummarizedExperiment"){
    cat("\n$RangedSummarizedExperiment:\n")
    print(x$RangedSummarizedExperiment)
  }
}
