#' Print EDY objects.
#'
#' @title Print EDY objects
#' @param x An EDY object generated by the function \code{getEDY}.
#' 
#' @export print.EDY 
#' @return A description of the contents of the EDY object (\code{x}).


print.EDY <- function(x, ...){
  cat("EDY object\nGenerated by `getEDY`\nContains information about males only from the original ExperessionSet\n")
  cat("$Ry: matrix. Expression of chrY genes relative to the rest of the genome\n")
  cat("  dim. ")
  cat(dim(x$Ry)[1])
  cat(" individuals (rows)  ")
  cat(dim(x$Ry)[2])
  cat(" genes (columns)")
  cat("\n$EDY: which individuals have extreme downregulation of chrY\n  YES: ")
  cat(table(x$EDY)[1])
  cat("  NO: ")
  cat(table(x$EDY)[2])
  cat("\n$threshold: ")
  cat(x$threshold)
  cat("\n$eSet:\n")
  x$eSet
}
